## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "D+M=💖"
copyright = "2023"
theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"

# Local
baseURL = "/"
publishDir = "docs"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Wedding celebration invitation website."
  logo = "images/flyer.jpg"
  favicon = true

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]

[_build]
  list = 'always'
  publishResources = true
  render = 'always'